### ISSUE TITLE
Cant download visits on current version 1.6

### ISSUE THREAD

**Issue by paulphilimone** [SwissTPH/openhds-tablet#10]
There is a bug generated on class SyncEntitiesTask that is doesnt allow to parse visits correctly.

Two lines 776 and 777 were added during commit: 06702d0daf7df2a68dd34ccb075fe1750b453659
These lines are triggering an error while reading the xml

A simple way to fix it is just comment them.
776. //parser.nextTag(); // <realVisit> 
777. //parser.nextText();

**Comment by aurdipas** [comment]
On update from 1.5 to 1.6 you need to update in the visit table the field realvisit=1. This will fix the issue. It is not a bug.

**Comment by paulphilimone** [comment]
Hi,

Thank you for the clarification!

One site was trying to implement OpenHDS, and they found problem downloading entities on visits.
(They probably are using wrong ODK visit form).

Is this field automatically filled via ODK - Mirth - OpenHDS process, or its necessary to flag realVisit=1 whenever I have new visit?

**Comment by aurdipas** [comment]
the latest visit form and the latest mirth channel manage automatically the realVisit flag

**Comment by paulphilimone** [comment]
Thank you!
