### ISSUE TITLE
Open Especific ODK Collect Form from Another App

### ISSUE THREAD

**Issue by matavele** [SwissTPH/openhds-tablet#13]
Hi, I want to open a specific form in ODK Collect. I don't know how to do it, the code below only opens the first form in the list.

Thanks in advance

```
Intent intent = new Intent(Intent.ACTION_EDIT);
intent.setData("content://org.odk.collect.android.provider.odk.forms/forms/2");
startActivity(intent);
```

**Comment by aurdipas** [comment]
this is implemented in the extra form. Please read the manual about it
