### ISSUE TITLE
Change of the head to household due to death

### ISSUE THREAD

**Issue by mainic00** [SwissTPH/openhds-tablet#3]
Currently changing the head of the household (HoH) is not automated, it requires data entry through the web interface (a form for collecting the relevant information is part of the tablet app). The following steps are proposed to automate changing the HoH.

Add tablet functionality:
If the HoH is selected, and Death is selected: Search to ask for new HoH (similar to search for Mother, Father of an individual), selection filtered for this HH.
Populate the XForm with the new HoH id, and (via loop), all remaining Members of the HH’s ids (make these read-only fields for id, firstname, lastname, dob, and a select-one question for relation to new HoH)

New Server functionality:
Add a webservice to change HoH, based on data from HoH change form:
Change the HoH_Id of the corresponding record in the socialgroup table (this is only a convenience field to look up the current HoH, the same information including history of HoHs is available from the membership table)
Update the membership table: set the endDate for the membership record of the deceased previous HoH. For each remaining member, set the endDate of the current membership record, and create a new record with startDate on the following day, with the relationship to HoH (field bIsToA) as collected in the form (except for the new HoH, which is set to 1=Head). TODO: define endType and startType for these memberships.
Update Mirth Channel (add destination) to transfer data from Aggregate to openHDS

**Comment by aurdipas** [comment]
in version 1.3
