### ISSUE TITLE
Pregnancy outcome not working 

### ISSUE THREAD

**Issue by Advocatus** [SwissTPH/openhds-tablet#8]
I am using the OpenHDS mobile apk version (openhds-tablets-1-3-1.apk) to perform the Pregnancy Outcome with the latest Pregnancy_outcome.xlsx, however when I open the ODK form through openHDS apk I get the following error message: "bind for /pregnancy_outcome/recordedDate contains invalid constrait expression [.<=today and > /pregnancy_outcome/earliestDate] Bad node:
org.javarosa.xpath.parser.ast.ASTNodeAbstractExpr@424f1430

Regards,

Advocatus

**Comment by aurdipas** [comment]
fixed any issue however this version of the form is not compatible with 1.3.1 apk. Only for 1.3.3 onward
